=== tensberg/jgloss-mirror/jgloss/src/data/export/export-descriptor.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--

 Copyright (C) 2002 Michael Koch (tensberg@gmx.net)

 This file is part of JGloss.

 JGloss is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 JGloss is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with JGloss; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 $Id$

-->

<!ELEMENT export (description,parameters?,localized-strings?,(template|templates))>

<!ELEMENT description (menuitem,title,file-extension?)>
<!ELEMENT menuitem EMPTY>
<!ATTLIST menuitem key CDATA #REQUIRED>
<!ELEMENT title EMPTY>
<!ATTLIST title key CDATA #REQUIRED>
<!ELEMENT file-extension (#PCDATA)>
<!ATTLIST file-extension description-key CDATA #REQUIRED>

<!ELEMENT parameters (encoding|boolean|string|combobox|docname|datetime)+>
<!ELEMENT docname (#PCDATA)>
<!ATTLIST docname name CDATA #REQUIRED>
<!ELEMENT datetime (#PCDATA)>
<!ATTLIST datetime name CDATA #REQUIRED>

<!ELEMENT encoding (#PCDATA)>
<!ATTLIST encoding label-key CDATA #REQUIRED
                   prefs-key CDATA #REQUIRED
                   name CDATA #REQUIRED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean label-key CDATA #REQUIRED
                  prefs-key CDATA #REQUIRED
                  name CDATA #REQUIRED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string label-key CDATA #REQUIRED
                 prefs-key CDATA #REQUIRED
                 name CDATA #REQUIRED>
<!ELEMENT combobox (comboitem)+>
<!ATTLIST combobox label-key CDATA #REQUIRED
                   prefs-key CDATA #REQUIRED
                   name CDATA #REQUIRED
                   editable (true|false) "false">
<!ELEMENT comboitem ((label|label-key)?,value)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT label-key (#PCDATA)>
<!ELEMENT value (#PCDATA)>

<!ELEMENT localized-strings (localized-string)+>
<!ELEMENT localized-string EMPTY>
<!ATTLIST localized-string key CDATA #REQUIRED
                           name CDATA #REQUIRED>

<!ELEMENT templates (template,template+)>
<!ATTLIST templates name CDATA "template-name"
                    label-key CDATA #REQUIRED
                    prefs-key CDATA #REQUIRED
                    editable (true|false) "false">

<!ELEMENT template ((label|label-key)?,source)>
<!ELEMENT source (#PCDATA)>

=== tensberg/jgloss-mirror/jgloss/src/data/export/html-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE export PUBLIC "JGloss export/1.0/JGloss export template description/EN"
                        "http://jgloss.sourceforge.net/export-descriptor.dtd">

<export>
  <description>
    <menuitem key="export.html.menu" />
    <title key="export.html.title" />
    <file-extension description-key="filefilter.description.html">html</file-extension>
  </description>

  <parameters>

    <encoding name="encoding"
      label-key="export.encodings" 
      prefs-key="export.html.encoding" 
      >UTF-8</encoding>

    <boolean name="writereadings"
      label-key="export.writereadings"
      prefs-key="export.html.writereadings"
      >true</boolean>

    <boolean name="writetranslations"
      label-key="export.writetranslations"
      prefs-key="export.html.writetranslations" 
      >true</boolean>

  </parameters>
  
  <template>
    <source>html.xslt</source>
  </template>
</export>

=== tensberg/jgloss-mirror/jgloss/src/data/export/annotationlist-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE export PUBLIC "JGloss export/1.0/JGloss export template description/EN"
                        "http://jgloss.sourceforge.net/export-descriptor.dtd">

<!--

 Copyright (C) 2003 Michael Koch (tensberg@gmx.net)

 This file is part of JGloss.

 JGloss is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 JGloss is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with JGloss; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 $Id$

-->

<export>
  <description>
    <menuitem key="export.annotationlist.menu" />
    <title key="export.annotationlist.title" />
  </description>

  <parameters>
    
    <encoding name="encoding"
      label-key="export.encodings" 
      prefs-key="export.annotationlist.encoding" 
      >UTF-8</encoding>
    
    <docname name="document-filename" />
    <datetime name="generation-time" />
 
  </parameters>
  
  <template>
    <source>annotationlist.xslt</source>
  </template>
</export>

=== tensberg/jgloss-mirror/jgloss/src/data/export/text-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE export PUBLIC "JGloss export/1.0/JGloss export template description/EN"
                        "http://jgloss.sourceforge.net/export-descriptor.dtd">

<export>
  <description>
    <menuitem key="export.text.menu" />
    <title key="export.text.title" />
  </description>

  <parameters>

    <encoding name="encoding"
      label-key="export.encodings" 
      prefs-key="export.text.encoding" 
      >UTF-8</encoding>

    <boolean name="writereadings"
      label-key="export.writereadings"
      prefs-key="export.text.writereadings"
      >true</boolean>

    <boolean name="writetranslations"
      label-key="export.writetranslations"
      prefs-key="export.text.writetranslations" 
      >false</boolean>

    <boolean name="voclist"
      label-key="export.text.voclist"
      prefs-key="export.text.voclist" 
      >true</boolean>

  </parameters>
  
  <template>
    <source>text.xslt</source>
  </template>
</export>

=== tensberg/jgloss-mirror/jgloss/src/main/resources/export/latex-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE export PUBLIC "JGloss export/1.0/JGloss export template description/EN"
                        "http://jgloss.sourceforge.net/export-descriptor.dtd">

<!--

 Copyright (C) 2002-2004 Michael Koch (tensberg@gmx.net)

 This file is part of JGloss.

 JGloss is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 JGloss is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with JGloss; if not, write to the Free Software
 Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

 $Id$

-->

<export>
  <description>
    <menuitem key="export.latex.menu" />
    <title key="export.latex.title" />
    <file-extension description-key="filefilter.description.latex">tex</file-extension>
  </description>

  <export-class>jgloss.ui.export.LaTeXExporter</export-class>

  <parameters>
    <docname name="document-filename" />
    <datetime name="generation-time" />
    <longest-annotation name="longest-word" type="dictionary-word" />
    <longest-annotation name="longest-reading" type="dictionary-reading" />

    <list name="font-size"
      label-key="export.latex.fontsize"
      prefs-key="export.latex.fontsize">
      <listitem><value>10</value></listitem>
      <listitem><value>11</value></listitem>
      <listitem><value>12</value></listitem>
    </list>

  </parameters>
  
  <templates label-key="export.templates" prefs-key="export.latex.templates">
    <template>
      <label-key>export.latex.template.platex-top</label-key>
      <source>platex-top.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.platex-list</label-key>
      <source>platex-list.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.platex-ruby</label-key>
      <source>platex-ruby.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-top</label-key>
      <source>latexcjk-top.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-list</label-key>
      <source>latexcjk-list.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-ruby</label-key>
      <source>latexcjk-ruby.tex.xslt</source>
    </template>
  </templates>
</export>

=== tensberg/jgloss-mirror/jgloss/src/data/export/latex-descriptor.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE export PUBLIC "JGloss export/1.0/JGloss export template description/EN"
                        "http://jgloss.sourceforge.net/export-descriptor.dtd">

<export>
  <description>
    <menuitem key="export.latex.menu" />
    <title key="export.latex.title" />
    <file-extension description-key="filefilter.description.latex">tex</file-extension>
  </description>

  <parameters>
    <docname name="docname" />
    <datetime name="creation-date" />

    <combobox name="fontsize"
      label-key="export.latex.fontsize"
      prefs-key="export.latex.fontsize">
      <comboitem><value>10</value></comboitem>
      <comboitem><value>11</value></comboitem>
      <comboitem><value>12</value></comboitem>
    </combobox>

  </parameters>
  
  <templates label-key="export.templates" prefs-key="export.latex.templates">
    <template>
      <label-key>export.latex.template.platex-top</label-key>
      <source>platex-top.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.platex-list</label-key>
      <source>platex-list.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.platex-ruby</label-key>
      <source>platex-ruby.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-top</label-key>
      <source>latexcjk-top.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-list</label-key>
      <source>latexcjk-list.tex.xslt</source>
    </template>
    <template>
      <label-key>export.latex.template.latexcjk-ruby</label-key>
      <source>latexcjk-ruby.tex.xslt</source>
    </template>
  </templates>
</export>
